export interface ListaPresupuestoResponse {
  programa: ProgramaL;
  presupuesto: PresupuestoL[];
}

export class PresupuestoL {
  id: number;
  idPresupuestoAnio: number
  idFinanciador: number;
  idPrograma: number;
  idProgramaCecos: number;
  anio: number;
  coberturaAnual: number;
  coberturaMensual: number;
  coberturaMensualEsperada: number;
  coberturasCasas: number;
}

export class ProgramaL {
  id: number;
  nombre: string;
  estado: boolean;
  fechaCreacion: string;
  fechaActualizacion: string;
}


// Generated by https://quicktype.io

export class PresupuestoListRequest {
    idPresupuesto: number;
}
