// Generated by https://quicktype.io

export interface UnicoProyecto {
    itemProyecto:      ItemProyecto;
    itemFinanciera:    ItemFinanciera;
    itemsFechas:       ItemsFecha[];
    itemsMunicipios:   ItemsMunicipio[];
    itemsEjecucion:    ItemsEjecucion[];
    itemsCentroCostos: ItemsCentroCosto[];
    itemProyectados:   ItemProyectados;
}

export interface ItemFinanciera {
    id:                 number;
    id_proyecto:        number;
    costoTotal:         number;
    fuente:             string;
    plataContrapartida: number;
    plataDonante:       number;
    tipoFuente:         string;
    monedaDonacion:     string;
    tasacambio:         string;
    cuenta:             string;
    navision:           string;
    responsable:        string;
    lugar:              string;
}

export interface ItemProyectados {
    id:            number;
    totalFamilias: number;
    observaciones: string;
}

export interface ItemProyecto {
    id:                  number;
    nombre:              string;
    status:              string;
    donante:             string;
    tipo_financiacion:   string;
    nombre_donante:      string;
    direccion:           string;
    email:               string;
    fecha_inicio:        string;
    fecha_finalizacion:  string;
    lider_ejecucion:     string;
    lider_coordinacion:  string;
    comite_tecnico:      string;
    requiereLiquidacion: boolean;
    archivo:             string;
    nombrearchivo:       string;
}

export interface ItemsCentroCosto {
    id:                number;
    id_SubCentroCosto: number;
    id_InfoFinanciera: number;
    id_Colaboradores:  null;
    codigo:            string;
}

export interface ItemsEjecucion {
    id:           number;
    idFinanciera: number;
    nombre:       string;
    enero:        number;
    febrero:      number;
    marzo:        number;
    abril:        number;
    mayo:         number;
    junio:        number;
    julio:        number;
    agosto:       number;
    sept:         number;
    octubre:      number;
    noviembre:    number;
    diciembre:    number;
}

export interface ItemsFecha {
    id:          number;
    id_proyecto: number;
    fecha:       string;
    tipo_fecha:  string;
}

export interface ItemsMunicipio {
    id:              number;
    id_proyecto:     number;
    id_departamento: number;
    id_municipio:    number;
}
