// Generated by https://quicktype.io

export interface UnicoProyecto {
    itemProyecto:      ItemProyecto;
    itemFinanciera:    ItemFinanciera;
    itemsFechas:       ItemsFecha[];
    itemsMunicipios:   ItemsMunicipio[];
    itemsEjecucion:    ItemsEjecucion[];
    itemsCentroCostos: ItemsCentroCosto[];
    itemProyectados:   ItemProyectados;
}

export class ItemFinanciera {
    id:                 number;
    id_proyecto:        number;
    costoTotal:         number;
    fuente:             string;
    plataContrapartida: number;
    plataDonante:       number;
    tipoFuente:         string;
    monedaDonacion:     string;
    tasacambio:         string;
    cuenta:             string;
    navision:           string;
    responsable:        string;
    lugar:              string;
}

export class ItemProyectados {
    id:                number;
    totalFamilias:     number;
    observaciones:     string;
    listParticipantes: ListParticipante[];
}

export interface ListParticipante {
    id:               number;
    id_participantes: number;
    nombre:           string;
    rango_0_5:        number;
    rango_6_12:       number;
    rango_13_17:      number;
    rango_18_24:      number;
    rango_25_56:      number;
    mayores_60:       number;
    total:            number;
    totalDesagregado: number;
    porcentaje:       number;
}


export interface ItemProyecto {
    id:                  number;
    nombre:              string;
    status:              string;
    donante:             string;
    tipo_financiacion:   string;
    nombre_donante:      string;
    direccion:           string;
    telefono:            string;
    email:               string;
    fecha_inicio:        string;
    fecha_finalizacion:  string;
    lider_ejecucion:     string;
    lider_coordinacion:  string;
    tipo_implementacion: string;
    comite_tecnico:      string;
    requiereLiquidacion: boolean;
    requiereLiquidacionv: string;

    archivo:             string;
    nombrearchivo:       string;
}

export interface ItemsCentroCosto {
    id:                number;
    id_SubCentroCosto: number;
    id_InfoFinanciera: number;
    id_Colaboradores:  null;
    codigo:            string;
}

export interface ItemsEjecucion {
    id:           number;
    idFinanciera: number;
    nombre:       string;
    enero:        number;
    febrero:      number;
    marzo:        number;
    abril:        number;
    mayo:         number;
    junio:        number;
    julio:        number;
    agosto:       number;
    sept:         number;
    octubre:      number;
    noviembre:    number;
    diciembre:    number;
}

export class ItemsFecha {
    id:          number;
    id_proyecto: number;
    fecha:       any;
    tipo_fecha:  string;
}

export interface ItemsMunicipio {
    id:              number;
    id_proyecto:     number;
    id_departamento: string;
    id_municipio:    string;
}


export class ItemProyectoRequest{
    ItemProyecto: ItemProyecto
}

export class ItemFinancieraRequest{
    ItemFinanciera: ItemFinanciera
}

export class ItemsFechaRequest{
    ItemsFechas: ItemsFecha
}

export class ListParticipanteRequest{
    listParticipantes: ListParticipante[];
}

export class ItemProyectadosRequest{
    ItemProyectados: ItemProyectados;
}