// Generated by https://quicktype.io

export interface IndicadoresResponse {
    indicadores: Indicadores[];
}

export interface Indicadores{
    id:                 number;
    nombreIndicador:    string;
    fechaCreacion:      string;
    fechaActualizacion: string;
}
