// Generated by https://quicktype.io

export interface IndicadoresPreguntasResponse {
    listaPreguntas: ListaPregunta[];
}


export interface ListaPregunta {
    indicador:      string;
    listaPreguntas: ListaPreguntaListaPregunta[];
}
export interface ListaPreguntaListaPregunta {
    encabezado: Preguntas;
    preguntas:  Preguntas[];
}

export interface Preguntas {
    id:                          number;
    id_indicador:                number;
    esPadre:                     boolean;
    descripcion:                 string;
    tipo:                        number;
    fechaCreacion:               string;
    fechaActualizacion:          string;
    complemento:                 Complemento[];
}

export interface Complemento {
    id:                 number;
    idPregunta:         number;
    opcion:             string;
    esOtro:             boolean;
    formValid?:         boolean;
    valorOtro?:         string;
    fechaCreacion:      string;
    fechaActualizacion: string;
}

