// Generated by https://quicktype.io

export interface RespuestaIndicadoresResponse {
    indicadoresParticipante: IndicadoresParticipante[];
}

export interface IndicadoresParticipante {
    id:                 number;
    nombreIndicador:    string;
    fechaCreacion:      string;
    fechaActualizacion: string;
}
