// Generated by https://quicktype.io

export class CoberturaRequest {
    constructor(){
        this.idPrograma = 0;
        this.idPrograma = 0;
        this.idCeco = 0;
    }
    idPrograma:        number;
    idPresupuestoAnio: number;
    idCeco:            number;
}
