insert into [Presupuesto].[dbo].[cargos](tipo, cod_cargo, cargo) VALUES
('Administrativo','11','ASISTENTE CONTABLE'),
('Administrativo','101','ANALISTA DE INFORMACION'),
('Administrativo','112','LIDER LOGISTICO'),
('Administrativo','148','SECRETARIA EJECUTIVA'),
('Administrativo','229','GESTOR@ LAO'),
('Administrativo','1','DIRECTORA NACIONAL'),
('Administrativo','3','ANALISTA SUPERVISION'),
('Administrativo','5','ASESOR DE ABOGACIA E'),
('Administrativo','7','ASESOR NACIONAL DE E'),
('Administrativo','10','ASISTENTE ATENCION A'),
('Administrativo','12','ASISTENTE DE DONANTE'),
('Administrativo','13','ASISTENTE SERVICIO A'),
('Administrativo','14','PROFESIONAL DE PADRI'),
('Administrativo','15','AUXILIAR ADMINISTRAT'),
('Administrativo','22','CONTADOR'),
('Administrativo','23','COORDINADOR DE ALIAN'),
('Administrativo','25','COORDINADOR FIDELIZA'),
('Administrativo','26','COORDINADOR NACIONAL'),
('Administrativo','27','COORDINADORA DE DONA'),
('Administrativo','30','DIRECTOR DESARROLLO '),
('Administrativo','31','DIRECTOR ENCARGADO'),
('Administrativo','32','DIRECTOR DE PROGRAMA'),
('Administrativo','33','DIRECTORA OFICINA DE'),
('Administrativo','54','RECEPCIONISTA'),
('Administrativo','59','RESPONSABLE INFORMAC'),
('Administrativo','61','SECRETARIA'),
('Administrativo','63','SUBDIRECTOR NACIONAL'),
('Administrativo','64','TECNICA ADMINISTRATI'),
('Administrativo','65','TECNICO EN NOMINA '),
('Administrativo','71','ADMINSTRADOR ON '),
('Administrativo','72','ASISTENTE DIRECCION '),
('Administrativo','73','TESORERA'),
('Administrativo','74','PROFESIONAL EN COMUN'),
('Administrativo','75','SUPERVISOR CONTAC CE'),
('Administrativo','76','DIRECTOR SOSTENIBILI'),
('Administrativo','77','PROFESIONAL DE SALUD'),
('Administrativo','79','COORDINADORA NAL. DE'),
('Administrativo','80','COORDINADOR NACIONAL'),
('Administrativo','81','COORDINADOR REGIONAL'),
('Administrativo','82','AUXILIAR LOGISTICO A'),
('Administrativo','83','ASISTENTE DE RALACIO'),
('Administrativo','84','PROF. DE ALIANZAS CO'),
('Administrativo','87','COORDINADORA DE COMU'),
('Administrativo','88','ASESOR REG DE RECUAD'),
('Administrativo','89','ASESOR NAC'),
('Administrativo','90','COORDINADOR PLANIFIC'),
('Administrativo','91','LIDER DE JURICO '),
('Administrativo','93','ASISTENTE ADMINISTRA'),
('Administrativo','102','DIRECTOR DE DESARROL'),
('Administrativo','103','AUXILIAR CONTABLE'),
('Administrativo','104','FACER JUNIOR'),
('Administrativo','105','TALLERISTA'),
('Administrativo','106','FACER SEÑIOR'),
('Administrativo','107','LIDER DE FACE TO FAC'),
('Administrativo','108','SUPERVISOR LOGISTICO'),
('Administrativo','109','PASANTE'),
('Administrativo','114','GERENTE DE REGIONAL'),
('Administrativo','116','COORDINADOR CONTABLE'),
('Administrativo','117','PROFESIONAL GEST COO'),
('Administrativo','119','COORDINADORA DE RECA'),
('Administrativo','120','DIGITADOR BASE DATOS'),
('Administrativo','121','DESARROLLADOR DE SOF'),
('Administrativo','124','PROF. JUNIOR DE COMU'),
('Administrativo','125','ASISTENTE LOGISTICA '),
('Administrativo','126','PROF. PLANEACION DE '),
('Administrativo','127','ASISTENTE DE TELEMER'),
('Administrativo','128','DIRECTOR DE PROYECTO'),
('Administrativo','129','SECRETARIA Y RESP IN'),
('Administrativo','130','AUXILIAR DE GESTION '),
('Administrativo','132','ASESOR FINANCIERO '),
('Administrativo','133','PROFESIONAL DE PROYE'),
('Administrativo','134','ASISTENTE JURIDICO'),
('Administrativo','135','ASESOR DE PROGRAMAS '),
('Administrativo','137','COORDINADORA DE PROY'),
('Administrativo','142','COORDINADORA DE DESA'),
('Administrativo','144','ASISTENTE FINANCIERO'),
('Administrativo','146','AUXILIAR OPERATIVO'),
('Administrativo','149','GESTOR DE INFORMACIO'),
('Administrativo','153','PROFESIONAL SEÑIOR C'),
('Administrativo','157','ASESORA NACIONAL DLL'),
('Administrativo','158','CONTADOR JUNIOR '),
('Administrativo','159','DESARROLLO DE FONDOS'),
('Administrativo','162','TALLERISTA - APOYO L'),
('Administrativo','163','PROFESIONAL DE SISTE'),
('Administrativo','164','GESTOR SERV. AL DONA'),
('Administrativo','165','TECNICO CIENCIAS INF'),
('Administrativo','168','PROFESIONAL DE RECUA'),
('Administrativo','173','PROFESIONAL SEÑIOR D'),
('Administrativo','178','COORDINADOR D LABORA'),
('Administrativo','184','ASESOR REGIONAL ALIA'),
('Administrativo','185','ASISTENTE DE SEGURID'),
('Administrativo','188','AUXILIAR JURIDICO '),
('Administrativo','189','RESP. DE ALIANZAS Y '),
('Administrativo','190','PROFESIONAL JURIDICO'),
('Administrativo','191','ASESOR TECNICO NACIO'),
('Administrativo','192','APOYO ADMINISTRATIVO'),
('Administrativo','194','AUXILIAR ADMINISTRAT'),
('Administrativo','199','COORDINADORA FINANCI'),
('Administrativo','200','DIRECTORA DE FINANZA'),
('Administrativo','203','ASISTENTE DE LOGISTI'),
('Administrativo','205','PROFESIONAL DE OPERA'),
('Administrativo','208','AGENTE DE RECUADO Y '),
('Administrativo','209','GESTOR MASTER SER. A'),
('Administrativo','210','GESTOR EN INNOVACION'),
('Administrativo','211','ASISTENTE DE COMUNIC'),
('Administrativo','216','PROFESIONAL EN COMUN'),
('Administrativo','220','PROFESIONAL CONTROL '),
('Administrativo','222','GESTOR DE ALIANZAS'),
('Administrativo','225','PROFESIONAL DE EXPER'),
('Administrativo','226','PROFESIONAL TECNICO '),
('Administrativo','227','PROFESIONAL WASH'),
('Administrativo','230','COORDINADOR DE SEGUI'),
('Administrativo','231','LIDER PRODUCTIVO'),
('Administrativo','233','COORDINADOR METODOLO'),
('Administrativo','234','COORDINADOR DE OPERA'),
('Administrativo','236','PROFESIONALDE CONT'),
('Administrativo','237','OFICIAL DE ENLACE Y '),
('Administrativo','238','COORDINADORA DE MONI'),
('Administrativo','241','ANALISTA DE COSTOS Y'),
('Administrativo','243','COORDINADORA LAO'),
('Administrativo','245','COORDINADORA DESARRO'),
('Administrativo','246','ASESORA NACIONAL DE '),
('Administrativo','248','PROFESIONAL LAO '),
('Administrativo','249','ANALISTA DE FORMACIO'),
('Administrativo','250','ASISTENTE DIRECCION '),
('Mama','44','MADRE COMUNITARIA '),
('Mama','45','MAMA SOS'),
('Tias','171','TIA COMUNITARIA '),
('Pedagogia','6','ASESOR FAMILIAR '),
('Pedagogia','9','ASESOR DE DESARROLLO'),
('Pedagogia','17','AUXILIAR DE ENFERMER'),
('Pedagogia','21','AUXILIAR PEDAGOGIA'),
('Pedagogia','28','COORDINADORA DE SERV'),
('Pedagogia','29','COORDINADORA SERVICI'),
('Pedagogia','34','DOCENTE '),
('Pedagogia','35','DOCENTE LICENCIADA'),
('Pedagogia','36','FACILITADOR DE DESAR'),
('Pedagogia','37','FACILITADOR DE DESAR'),
('Pedagogia','38','FACILITADOR DESARROL'),
('Pedagogia','39','FACILITADORA DE COMU'),
('Pedagogia','40','FACILITADORA DE DESA'),
('Pedagogia','41','FACILITADORA DE DESA'),
('Pedagogia','42','FACILITADORA DE DESA'),
('Pedagogia','43','FACILITADORA FAMILIA'),
('Pedagogia','48','NUTRICIONISTA '),
('Pedagogia','50','PROFESIONAL PEDAGOGI'),
('Pedagogia','51','PROFESIONAL RESPONSA'),
('Pedagogia','52','PROMOTORA SOCIAL'),
('Pedagogia','53','PROTOMOTOR EN AGROEC'),
('Pedagogia','55','RESPONSABLE DE APOYO'),
('Pedagogia','56','RESPONSABLE DE ASEGU'),
('Pedagogia','57','RESPONSABLE DE DESAR'),
('Pedagogia','58','RESPONSABLE DE SALUD'),
('Pedagogia','60','RESPONSABLE VINCULAC'),
('Pedagogia','66','TERAPEUTA '),
('Pedagogia','70','TRABAJADORA SOCIAL'),
('Pedagogia','85','PROF FACICILITADORA'),
('Pedagogia','92','COORDINADOR PEDAGOGIA'),
('Pedagogia','96','ASISTENTE FAMILIAR'),
('Pedagogia','97','COORDINADORA DLLO Y'),
('Pedagogia','98','EDUCADORA DE APOYO'),
('Pedagogia','100','Responsable de atención'),
('Pedagogia','110','EDUCADOR'),
('Pedagogia','113','PSICOLOGO CLINICO'),
('Pedagogia','115','DIRECTORA DE SERVICIOS'),
('Pedagogia','122','APOYO PSICOSOCIAL'),
('Pedagogia','123','COORDINADORA DE FLIAS'),
('Pedagogia','136','PROFESIONAL PSICOSOCIAL'),
('Pedagogia','138','PSICOLOGA'),
('Pedagogia','139','RESPONSABLE DE DLLO '),
('Pedagogia','140','FORMADORA DIURNO ATE'),
('Pedagogia','141','CUIDADOR ESPECIALIZA'),
('Pedagogia','147','ASESOR DE COOEPRACIO'),
('Pedagogia','150','COORDINADOR DE FLIAS'),
('Pedagogia','151','PEDAGOGO'),
('Pedagogia','152','FACILITADOR DE FAMILA'),
('Pedagogia','155','EDUCADORA - ENFERMERO'),
('Pedagogia','160','EDUCADORA - ENFERMERO'),
('Pedagogia','161','EDUCADORA COM JUVENIL'),
('Pedagogia','169','EDUCADOR DE APOYO'),
('Pedagogia','187','EDUCADORA'),
('Pedagogia','204','PROFESIONAL DE CAMPO'),
('Pedagogia','206','PROFESIONAL JUNIOR'),
('Pedagogia','215','FACILITADOR DE ACOMP'),
('Pedagogia','224','EDUCADOR SEÑIOR'),
('Pedagogia','228','EDUCADOR JUNIOR'),
('Pedagogia','232','LIDER DEL COMPONENTE'),
('Pedagogia','235','LIDER DE SERVICIOS'),
('Pedagogia','239','DINAMIZADOR'),
('Pedagogia','240','FACILITADOR PROYECTO'),
('Pedagogia','242','ACOMPAÑANTE PEDAGOGIA'),
('Pedagogia','247','INSPIRADORA'),
('Servicios Generales','16','AUXILIAR DE ASEO'),
('Servicios Generales','18','AUXILIAR DE MANTENIM'),
('Servicios Generales','19','AUXILIAR DE SERVICIO'),
('Servicios Generales','20','AUXILIAR DE SERVICIO'),
('Servicios Generales','46','MANIPULADORA ALIMENT'),
('Servicios Generales','47','MENSAJERO COBRADOR'),
('Servicios Generales','62','SERVICIOS GENERALES'),
('Servicios Generales','99','JARDINERO'),
('Servicios Generales','193','MAYORDOMO'),
('Servicios Generales','202','CONDUCTOR'),
('Tias','86','POSTULANTE TIA SOS'),
('Tias','49','POSTULANTE'),
('Tias','67','TIA DE RELEVO'),
('Tias','68','RESPONSABLE DE FAMILA'),
('Tias','69','TIA SOS'),
('Tias','111','TIA DE FAMILIA'),
('Tias','170','TIA DE VACACIONES'),
('Tias','186','TIA DE APOYO'),
('Tias','212','EDUCADORA DE EMERGEN'),
('TIC','8','ASESOR NACIONAL DE T'),
('TIC','252','TECNICO SOPORTE ICT ')