// Generated by https://quicktype.io

export interface ColaboradorResponse {
    itemsColaboradores: ItemsColaboradores[];
}

export interface ItemsColaboradores {
    id:              number;
    idProyecto:      number;
    nombre:          string;
    fechaNacimiento: string;
    cargo:           string;
    tiempo:          string;
    tipoContrato:    string;
    fechaInicio:     string;
    fechaFin:        string;
    costoMensual:    number;
    porcentaje:      number;
    contrapartida:   number;
    aporte:          number;
}
