// Generated by https://quicktype.io

export interface ColaboradorResponse {
    itemsColaboradores: ItemsColaboradores[];
}

export class ItemsColaboradores {
    id:              number;
    idProyecto:      number;
    nombre:          string;
    fechaNacimiento: Date;
    fecha:           Date;

    cargo:           string;
    tiempo:          string;
    tipoContrato:    string;
    fechaInicio:     Date;
    fechaFin:        Date;
    costoMensual:    number;
    porcentaje:      number;
    contrapartida:   number;
    aporte:          number;
}
