import { ItemsColaboradores } from './colaborador.response';
// Generated by https://quicktype.io

export interface ColaboradorDetalleResponse {
    item:             ItemsColaboradores;
    itemsCentroCosto: ItemsCentroCosto[];
}

export interface ItemsCentroCosto {
    id:                number;
    id_SubCentroCosto: number;
    id_Colaboradores:  number;
    codigo:            string;
}
